apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexusdeploy

resources:
  # Namespace
  - namespace.yaml
  # Ingress
  - ingress.yaml
  # API Gateway
  - api-gateway/configmap.yaml
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml
  - api-gateway/hpa.yaml
  - api-gateway/networkpolicy.yaml
  # Auth Service
  - auth-service/configmap.yaml
  - auth-service/deployment.yaml
  - auth-service/service.yaml
  - auth-service/hpa.yaml
  - auth-service/networkpolicy.yaml
  # Worker Service
  - worker-service/configmap.yaml
  - worker-service/deployment.yaml
  - worker-service/service.yaml
  - worker-service/hpa.yaml
  - worker-service/networkpolicy.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: nexusdeploy
