apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: api-gateway-pdb
  namespace: nexusdeploy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: api-gateway
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth-service-pdb
  namespace: nexusdeploy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: auth-service
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: worker-service-pdb
  namespace: nexusdeploy
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: worker-service
