apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namespace: nexusdeploy-staging

commonLabels:
  environment: staging

patches:
  # api-gateway: 2 replicas
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: api-gateway
        namespace: nexusdeploy-staging
      spec:
        replicas: 2
  # auth-service: 2 replicas
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: auth-service
        namespace: nexusdeploy-staging
      spec:
        replicas: 2
  # worker-service: 2 replicas
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: worker-service
        namespace: nexusdeploy-staging
      spec:
        replicas: 2
  # HPA: moderate scaling
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: api-gateway
        namespace: nexusdeploy-staging
      spec:
        minReplicas: 2
        maxReplicas: 6
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: auth-service
        namespace: nexusdeploy-staging
      spec:
        minReplicas: 2
        maxReplicas: 5
  - patch: |-
      apiVersion: autoscaling/v2
      kind: HorizontalPodAutoscaler
      metadata:
        name: worker-service
        namespace: nexusdeploy-staging
      spec:
        minReplicas: 2
        maxReplicas: 8

configMapGenerator:
  - name: api-gateway-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
  - name: auth-service-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
  - name: worker-service-config
    behavior: merge
    literals:
      - ENVIRONMENT=staging
