{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "nexusdeploy.serviceAccountName" . }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "nexusdeploy.labels" . | nindent 4 }}
  {{- if .Values.serviceAccount.gcpServiceAccountEmail }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gcpServiceAccountEmail | quote }}
  {{- end }}
{{- end }}
